// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebRequesterData.Models;

namespace WebRequesterData.Models
{
    public partial interface IWebRequesterContextProcedures
    {
        Task<int> pageLinkInsertSpAsync(int? pageId, int? linkId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
