// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebRequesterData.Models;

public partial class pageTbl
{
    public int id { get; set; }

    public string url { get; set; }

    public virtual ICollection<pageLinkTbl> pageLinkTbllink { get; set; } = new List<pageLinkTbl>();

    public virtual ICollection<pageLinkTbl> pageLinkTblpage { get; set; } = new List<pageLinkTbl>();
}