// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebRequesterData.Models;

public partial class pageLinkTbl
{
    public int pageId { get; set; }

    public int linkId { get; set; }

    public DateTime lastFoundTimeStamp { get; set; }

    public virtual pageTbl link { get; set; }

    public virtual pageTbl page { get; set; }
}