// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebRequesterData.Models;

public partial class WebRequesterContext : DbContext
{
    public WebRequesterContext(DbContextOptions<WebRequesterContext> options)
        : base(options)
    {
    }

    public virtual DbSet<pageLinkTbl> pageLinkTbl { get; set; }

    public virtual DbSet<pageTbl> pageTbl { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<pageLinkTbl>(entity =>
        {
            entity.HasKey(e => new { e.pageId, e.linkId });

            entity.Property(e => e.lastFoundTimeStamp)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_pageLinkTbl_lastFoundTimeStamp");

            entity.HasOne(d => d.link).WithMany(p => p.pageLinkTbllink)
                .HasForeignKey(d => d.linkId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_pageLinkTbl_pageTbl1");

            entity.HasOne(d => d.page).WithMany(p => p.pageLinkTblpage)
                .HasForeignKey(d => d.pageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_pageLinkTbl_pageTbl");
        });

        modelBuilder.Entity<pageTbl>(entity =>
        {
            entity.HasIndex(e => e.md5, "IX_pageTbl");

            entity.Property(e => e.addedTimeStamp)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_pageTbl_addedTimeStamp");
            entity.Property(e => e.errorMessage)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_pageTbl_errorMessage");
            entity.Property(e => e.html)
                .IsRequired()
                .IsUnicode(false)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_pageTbl_html");
            entity.Property(e => e.md5)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.updatedTimeStamp)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_pageTbl_updatedTimeStamp");
            entity.Property(e => e.url)
                .IsRequired()
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}