// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebRequesterData.Models;

namespace WebRequesterData.Models
{
    public partial class WebRequesterContext
    {
        private IWebRequesterContextProcedures _procedures;

        public virtual IWebRequesterContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new WebRequesterContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IWebRequesterContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class WebRequesterContextProcedures : IWebRequesterContextProcedures
    {
        private readonly WebRequesterContext _context;

        public WebRequesterContextProcedures(WebRequesterContext context)
        {
            _context = context;
        }

        public virtual async Task<int> pageLinkInsertSpAsync(int? pageId, int? linkId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "pageId",
                    Value = pageId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "linkId",
                    Value = linkId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[pageLinkInsertSp] @pageId = @pageId, @linkId = @linkId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
